global:
  scrape_interval: 15s

rule_files: []

scrape_configs:
  - job_name: 'spring-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: "prometheus"
